# pf_equipment_constants.gd
## System-wide constants for item materials, grades, and runes.
class_name PFEquipmentConstants

enum WeaponType { MELEE, RANGED }
enum WeaponCategory { UNARMED, SIMPLE, MARTIAL, ADVANCED }
enum WeaponGroup { AXE, BOMB, BOW, BRAWLING, CLUB, CROSSBOW, DART, FIREARM, FLAIL, HAMMER, KNIFE, PICK, POLEARM, SHIELD, SLING, SPEAR, SWORD, NONE }
enum PotencyRune { NONE, PLUS_ONE, PLUS_TWO, PLUS_THREE }
enum StrikingRune { NONE, STRIKING, GREATER, MAJOR }
enum ReinforcingRune { NONE, MINOR, LESSER, MODERATE, GREATER, MAJOR, SUPREME }
enum ItemMaterial { STANDARD, WOOD, IRON, STEEL, COLD_IRON, SILVER, ADAMANTINE, MITHRAL, DRAGONHIDE, ORICHALCUM }
enum MaterialGrade { LOW, STANDARD, HIGH }
enum ArmorCategory { UNARMORED, LIGHT, MEDIUM, HEAVY }
enum ArmorGroup { UNARMORED, CLOTH, LEATHER, CHAIN, COMPOSITE, PLATE }
enum ResilientRune { NONE, RESILIENT, GREATER, MAJOR }
enum PropertyRune { FLAMING, FROST, SHOCK, CORROSIVE, GHOST_TOUCH, RETURNING, SHIFTING, WOUNDING, DISRUPTING }
enum AmmunitionType { NONE, ARROWS, BOLTS, BULLETS, SLING_BULLETS }
